# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a993dd3c93f67888b06fb7b83babeaf48c30c707d58eac3723d67b74b40a54029296adfb48f93ccc24b2ac0471928a70040454f1ac088d2a6e4c6424fb0aedea

test:
  secret_key_base: 3b02b087c18fb50cdf1a2960a7e8ebfc2e280d2cba7766a3f53bf0ef9e0a324cc64614024a2c04a6c96efb99da398547bddfdf9f4936e3c959781f233514e667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
